Minor rearrangement: files not intended for direct inclusion now movet to internal/ and named .hh
Remove stride from SDVbase.

Removed delete[] from SDVBase.

Added in some bounds checking.

Added in some slicing, with static slice checking.

The splitting up of the slice checking in to s different include file gives
slightly nicer error messages with gcc, since the file name appears in the
first column:

./TooN/internal/slice_error.hh: In static member function 'static void TooN::Internal::CheckSlice<Size, Start, Length>::check() [with int Size = 3, int Start = 1, int Length = 2]':
./TooN/internal/vector.hh:61:   instantiated from 'TooN::Vector<Length, TooN::SVBase<Length, 1> > TooN::VBase<Size, 0>::slice() [with int Start = 1, int Length = 2, int Size = 3]'
TooN/test/vec_test.cc:22:   instantiated from here
./TooN/internal/slice_error.hh:16: error: incomplete type 'TooN::Internal::BadSlice<3, true>' used in nested name specifier